# Generated by Django 5.2.7 on 2025-10-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elms', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
